name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'

      - name: Setup Elm
        uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1

      - name: Build Elm
        run: make elm

      - name: Replace commit hash and Elasticsearch URL
        run: |
          mv ./app.js ./app-${{ github.sha }}.js
          sed -i -e 's/app.js/app-${{ github.sha }}.js/' ./index.html
          sed -i -e 's/localhost/34.88.251.51/' ./index.html

      - name: Move files
        run: |
          mkdir ./build
          mv ./index.html ./app-${{ github.sha }}.js ./build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          force_orphan: true
          enable_jekyll: true
